# Generated by Django 6.0.2 on 2026-02-17 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='출제연도')),
                ('number', models.IntegerField(verbose_name='문항번호')),
                ('text', models.TextField(verbose_name='문제')),
                ('choice_1', models.CharField(max_length=200, verbose_name='보기①')),
                ('choice_2', models.CharField(max_length=200, verbose_name='보기②')),
                ('choice_3', models.CharField(max_length=200, verbose_name='보기③')),
                ('choice_4', models.CharField(max_length=200, verbose_name='보기④')),
                ('answer', models.IntegerField(choices=[(1, '①'), (2, '②'), (3, '③'), (4, '④')], verbose_name='정답')),
                ('explanation', models.TextField(blank=True, verbose_name='정답 설명')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '기출문제',
                'verbose_name_plural': '기출문제',
                'ordering': ['subject', 'year', 'number'],
                'unique_together': {('subject', 'year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.IntegerField(choices=[(1, '①'), (2, '②'), (3, '③'), (4, '④')], verbose_name='선택한 답')),
                ('is_correct', models.BooleanField(verbose_name='정답여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='풀이시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='문제')),
            ],
            options={
                'verbose_name': '풀이기록',
                'verbose_name_plural': '풀이기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
