# Generated by Django 6.0.2 on 2026-02-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('main', '0002_subject_category_subject_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='출제연도')),
                ('exam_type', models.CharField(choices=[('중간', '중간고사'), ('기말', '기말고사'), ('계절', '계절학기')], max_length=10, verbose_name='시험종류')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '시험',
                'verbose_name_plural': '시험',
                'ordering': ['subject', '-year', 'exam_type'],
                'unique_together': {('subject', 'year', 'exam_type')},
            },
        ),
    ]
