# Generated by Django 6.0.2 on 2026-02-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-year', 'exam_type'], 'verbose_name': '시험', 'verbose_name_plural': '시험'},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('year', 'exam_type')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
