# Generated by Django 6.0.2 on 2026-02-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_options_alter_exam_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='selected',
            field=models.IntegerField(choices=[(0, '미확인'), (1, '①'), (2, '②'), (3, '③'), (4, '④')], verbose_name='선택한 답'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(0, '미확인'), (1, '①'), (2, '②'), (3, '③'), (4, '④')], verbose_name='정답'),
        ),
    ]
