# Generated by Django 6.0.2 on 2026-02-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_attempt_selected_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_1',
            field=models.TextField(verbose_name='보기①'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_2',
            field=models.TextField(verbose_name='보기②'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_3',
            field=models.TextField(verbose_name='보기③'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_4',
            field=models.TextField(verbose_name='보기④'),
        ),
    ]
