# Generated by Django 6.0.2 on 2026-02-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_question_choice_1_alter_question_choice_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_1_exp',
            field=models.TextField(blank=True, verbose_name='보기① 해설'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2_exp',
            field=models.TextField(blank=True, verbose_name='보기② 해설'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3_exp',
            field=models.TextField(blank=True, verbose_name='보기③ 해설'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4_exp',
            field=models.TextField(blank=True, verbose_name='보기④ 해설'),
        ),
    ]
