# Generated by Django 6.0.2 on 2026-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_choice_1_exp_question_choice_2_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='selected',
            field=models.CharField(choices=[('0', '미확인'), ('1', '①'), ('2', '②'), ('3', '③'), ('4', '④'), ('1,2', '①②'), ('1,3', '①③'), ('1,4', '①④'), ('2,3', '②③'), ('2,4', '②④'), ('3,4', '③④'), ('1,2,3', '①②③'), ('1,2,4', '①②④'), ('1,3,4', '①③④'), ('2,3,4', '②③④'), ('1,2,3,4', '①②③④')], default='0', max_length=10, verbose_name='선택한 답'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('0', '미확인'), ('1', '①'), ('2', '②'), ('3', '③'), ('4', '④'), ('1,2', '①②'), ('1,3', '①③'), ('1,4', '①④'), ('2,3', '②③'), ('2,4', '②④'), ('3,4', '③④'), ('1,2,3', '①②③'), ('1,2,4', '①②④'), ('1,3,4', '①③④'), ('2,3,4', '②③④'), ('1,2,3,4', '①②③④')], default='0', max_length=10, verbose_name='정답'),
        ),
    ]
