# Generated by Django 6.0.2 on 2026-02-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_attempt_selected_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('exam', '풀이모드'), ('mock', '모의고사')], default='exam', max_length=10, verbose_name='풀이유형'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='세션ID'),
        ),
    ]
