# Generated by Django 6.0.2 on 2026-02-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_attempt_mode_attempt_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('exam', '풀이모드'), ('mock', '모의고사'), ('wrong_retry', '오답재풀이')], default='exam', max_length=20, verbose_name='풀이유형'),
        ),
    ]
