# Generated by Django 6.0.2 on 2026-02-24 00:24

from django.db import migrations


def set_created_by(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Question = apps.get_model("exam", "Question")

    # 김상현 유저 찾기 (first_name 또는 username)
    user = User.objects.filter(first_name="김상현").first()
    if not user:
        user = User.objects.filter(username="gocompu21").first()
    if not user:
        return

    # 최신기출 (year >= 2020) 중 created_by가 없는 문제에 등록자 설정
    Question.objects.filter(year__gte=2020, created_by__isnull=True).update(
        created_by=user
    )


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0011_question_created_by"),
    ]

    operations = [
        migrations.RunPython(set_created_by, migrations.RunPython.noop),
    ]
