# Generated by Django 6.0.2 on 2026-02-24 00:26

from django.db import migrations, models


def set_latest_name(apps, schema_editor):
    """최신기출(year>=2020)의 created_by_name을 '김상현'으로 설정"""
    Question = apps.get_model("exam", "Question")
    Question.objects.filter(year__gte=2020).update(created_by_name="김상현")


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0012_set_latest_created_by"),
    ]

    operations = [
        # 1. CharField 추가
        migrations.AddField(
            model_name="question",
            name="created_by_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="등록자"),
        ),
        # 2. 최신기출 등록자 이름 설정
        migrations.RunPython(set_latest_name, migrations.RunPython.noop),
        # 3. FK 제거
        migrations.RemoveField(
            model_name="question",
            name="created_by",
        ),
    ]
