# Generated by Django 6.0.2 on 2026-09-08 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_question_created_at'),
        ('main', '0011_qna_note_sec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('card_no', models.PositiveIntegerField(verbose_name='카드 번호')),
                ('name', models.CharField(max_length=50, verbose_name='잡초명')),
                ('family', models.CharField(blank=True, default='', max_length=50, verbose_name='과')),
                ('life_form', models.CharField(blank=True, default='', max_length=50, verbose_name='생활형')),
                ('habitat', models.CharField(blank=True, default='', max_length=100, verbose_name='발생지')),
                ('features', models.TextField(blank=True, default='', verbose_name='식별 포인트')),
                ('similar', models.TextField(blank=True, default='', verbose_name='유사종 구별')),
                ('control', models.TextField(blank=True, default='', verbose_name='방제·비고')),
                ('notes', models.TextField(blank=True, default='', verbose_name='교수 메모')),
                ('exam_count', models.PositiveIntegerField(default=0, verbose_name='출제 횟수')),
                ('q_image', models.ImageField(blank=True, upload_to='weeds/', verbose_name='문제 사진')),
                ('a_image', models.ImageField(blank=True, upload_to='weeds/', verbose_name='답 슬라이드')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weed_cards', to='main.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '잡초 카드',
                'verbose_name_plural': '잡초 카드',
                'ordering': ['subject', 'order'],
                'unique_together': {('subject', 'card_no')},
            },
        ),
        migrations.CreateModel(
            name='WeedQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='풀이 시각')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.weedcard', verbose_name='카드')),
                ('selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exam.weedcard', verbose_name='고른 카드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '잡초 퀴즈 기록',
                'verbose_name_plural': '잡초 퀴즈 기록',
                'indexes': [models.Index(fields=['user', 'card', '-id'], name='exam_weedqu_user_id_f2f2f9_idx')],
            },
        ),
    ]
