# Generated by Django 6.0.2 on 2026-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_weedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedcard',
            name='sketch_image',
            field=models.ImageField(blank=True, upload_to='weeds/', verbose_name='손그림'),
        ),
    ]
