# Generated by Django 6.0.2 on 2026-05-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='열람 시각')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_logs', to='bbs.notice', verbose_name='공지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_opens', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '메일 열람 기록',
                'verbose_name_plural': '메일 열람 기록',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['notice', 'user'], name='bbs_noticeo_notice__58397d_idx'), models.Index(fields=['opened_at'], name='bbs_noticeo_opened__a2de5c_idx')],
            },
        ),
    ]
