# Generated by Django 6.0.2 on 2026-06-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_password_changed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인 시각'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signups', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='관리자 승인'),
        ),
    ]
