# Generated by Django 6.0.2 on 2026-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_approve_existing_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cohort',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='기수'),
        ),
    ]
