# Generated by Django 6.0.2 on 2026-03-28 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/', verbose_name='PDF 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': 'PDF 파일',
                'verbose_name_plural': 'PDF 파일',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
