# Generated by Django 6.0.2 on 2026-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='과목명')),
                ('grade', models.IntegerField(choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년')], verbose_name='학년')),
                ('semester', models.IntegerField(choices=[(1, '1학기'), (2, '2학기')], verbose_name='학기')),
            ],
            options={
                'verbose_name': '교과과목',
                'verbose_name_plural': '교과과목',
                'ordering': ['grade', 'semester', 'name'],
            },
        ),
    ]
