# Generated by Django 6.0.2 on 2026-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('전공', '전공'), ('교양', '교양')], default='전공', max_length=10, verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(default='농학과', max_length=50, verbose_name='학과'),
        ),
    ]
