# Generated by Django 6.0.2 on 2026-05-02 11:31

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_examreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='자료 제목')),
                ('file', models.FileField(upload_to=main.models._material_upload_path, verbose_name='PDF 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.subject', verbose_name='과목')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '교과목 자료',
                'verbose_name_plural': '교과목 자료',
                'ordering': ['-created_at'],
            },
        ),
    ]
