# Generated by Django 6.0.2 on 2026-05-11 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subjectmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='열람 시각')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_logs', to='main.subjectmaterial', verbose_name='자료')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_opens', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'PDF 열람 기록',
                'verbose_name_plural': 'PDF 열람 기록',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['material', 'user'], name='main_materi_materia_8898d1_idx'), models.Index(fields=['opened_at'], name='main_materi_opened__05ccf1_idx')],
            },
        ),
    ]
