# Generated by Django 6.0.2 on 2026-05-11 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_materialopenlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialopenlog',
            options={'ordering': ['-opened_at'], 'verbose_name': 'PDF 열람·인쇄 기록', 'verbose_name_plural': 'PDF 열람·인쇄 기록'},
        ),
        migrations.AddField(
            model_name='materialopenlog',
            name='action',
            field=models.CharField(choices=[('view', '열람'), ('print', '인쇄')], default='view', max_length=10, verbose_name='동작'),
        ),
        migrations.AlterField(
            model_name='materialopenlog',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='시각'),
        ),
        migrations.AddIndex(
            model_name='materialopenlog',
            index=models.Index(fields=['action'], name='main_materi_action_29be71_idx'),
        ),
    ]
