# Generated by Django 6.0.2 on 2026-06-07 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_materialopenlog_options_materialopenlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(blank=True, default='', max_length=20, verbose_name='탭')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='시각')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='main.subject', verbose_name='과목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_views', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '과목 페이지 조회',
                'verbose_name_plural': '과목 페이지 조회',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='main_subjec_viewed__78b327_idx'), models.Index(fields=['user', 'viewed_at'], name='main_subjec_user_id_c2b8b0_idx'), models.Index(fields=['subject', 'tab', 'viewed_at'], name='main_subjec_subject_432fae_idx')],
            },
        ),
    ]
