# Generated by Django 6.0.2 on 2026-09-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subjectviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(blank=True, default='', max_length=50, verbose_name='자격증')),
                ('cert_subject', models.CharField(blank=True, default='', max_length=50, verbose_name='기사 과목')),
                ('title', models.CharField(max_length=200, verbose_name='질문')),
                ('body', models.TextField(blank=True, default='', verbose_name='보충 설명')),
                ('answer', models.TextField(blank=True, default='', verbose_name='답변')),
                ('answer_model', models.CharField(blank=True, default='', max_length=40, verbose_name='모델')),
                ('note_ref', models.CharField(blank=True, default='', max_length=200, verbose_name='참고 노트')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변 시각')),
                ('error', models.CharField(blank=True, default='', max_length=200, verbose_name='오류')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('flagged', models.PositiveIntegerField(default=0, verbose_name='신고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.subject', verbose_name='과목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_questions', to=settings.AUTH_USER_MODEL, verbose_name='질문자')),
            ],
            options={
                'verbose_name': '질의응답',
                'verbose_name_plural': '질의응답',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QnaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='시각')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='main.qnaquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '질문 조회',
                'verbose_name_plural': '질문 조회',
            },
        ),
        migrations.AddIndex(
            model_name='qnaquestion',
            index=models.Index(fields=['subject', '-created_at'], name='main_qnaque_subject_5dcdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='qnaquestion',
            index=models.Index(fields=['cert_name', '-created_at'], name='main_qnaque_cert_na_ef734a_idx'),
        ),
        migrations.AddIndex(
            model_name='qnaquestion',
            index=models.Index(fields=['user', '-created_at'], name='main_qnaque_user_id_3a57c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qnaview',
            unique_together={('question', 'user')},
        ),
    ]
