# Generated by Django 6.0.2 on 2026-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_qnaquestion_qnaview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaquestion',
            name='note_sec',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='연결 절 번호'),
        ),
        migrations.AddField(
            model_name='qnaquestion',
            name='note_sec_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='연결 절 제목'),
        ),
    ]
