# Generated by Django 6.0.2 on 2026-02-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자격증명')),
                ('category', models.CharField(choices=[('기사', '기사'), ('산업기사', '산업기사'), ('기능사', '기능사'), ('기능장', '기능장'), ('기술사', '기술사')], default='기사', max_length=20, verbose_name='등급')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '자격증',
                'verbose_name_plural': '자격증',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='GisaExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='출제연도')),
                ('round', models.IntegerField(default=1, verbose_name='회차')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='시험일자')),
                ('exam_type', models.CharField(choices=[('필기', '필기'), ('실기', '실기')], default='필기', max_length=10, verbose_name='시험유형')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.certification', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '시험회차',
                'verbose_name_plural': '시험회차',
                'ordering': ['-year', '-round'],
                'unique_together': {('certification', 'year', 'round', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='GisaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='문항번호')),
                ('text', models.TextField(verbose_name='문제')),
                ('choice_1', models.TextField(verbose_name='보기①')),
                ('choice_2', models.TextField(verbose_name='보기②')),
                ('choice_3', models.TextField(verbose_name='보기③')),
                ('choice_4', models.TextField(verbose_name='보기④')),
                ('answer', models.CharField(choices=[('0', '미확인'), ('1', '①'), ('2', '②'), ('3', '③'), ('4', '④')], default='0', max_length=10, verbose_name='정답')),
                ('explanation', models.TextField(blank=True, verbose_name='정답 설명')),
                ('choice_1_exp', models.TextField(blank=True, verbose_name='보기① 해설')),
                ('choice_2_exp', models.TextField(blank=True, verbose_name='보기② 해설')),
                ('choice_3_exp', models.TextField(blank=True, verbose_name='보기③ 해설')),
                ('choice_4_exp', models.TextField(blank=True, verbose_name='보기④ 해설')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisaexam', verbose_name='시험')),
            ],
            options={
                'verbose_name': '기출문제',
                'verbose_name_plural': '기출문제',
                'ordering': ['exam', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GisaAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(default='0', max_length=10, verbose_name='선택한 답')),
                ('is_correct', models.BooleanField(verbose_name='정답여부')),
                ('mode', models.CharField(choices=[('exam', '풀이모드'), ('mock', '모의고사'), ('wrong_retry', '오답재풀이')], default='exam', max_length=20, verbose_name='풀이유형')),
                ('session_id', models.CharField(blank=True, default='', max_length=36, verbose_name='세션ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='풀이시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisaquestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': '풀이기록',
                'verbose_name_plural': '풀이기록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GisaSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='과목명')),
                ('order', models.IntegerField(default=1, verbose_name='과목순서')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.certification', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목',
                'ordering': ['certification', 'order'],
                'unique_together': {('certification', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gisaquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisasubject', verbose_name='과목'),
        ),
        migrations.AlterUniqueTogether(
            name='gisaquestion',
            unique_together={('exam', 'number')},
        ),
    ]
