# Generated by Django 6.0.2 on 2026-02-22 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaTextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='마크다운 내용')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.certification', verbose_name='자격증')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisasubject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재',
                'unique_together': {('certification', 'subject')},
            },
        ),
    ]
