# Generated by Django 6.0.2 on 2026-02-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0002_gisatextbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaexam',
            name='exam_type',
            field=models.CharField(choices=[('필기', '필기'), ('실기', '실기'), ('최신', '최신기출')], default='필기', max_length=10, verbose_name='시험유형'),
        ),
    ]
