# Generated by Django 6.0.2 on 2026-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0003_alter_gisaexam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaquestion',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='등록자'),
        ),
    ]
