# Generated by Django 6.0.2 on 2026-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0004_gisaquestion_created_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일'),
        ),
    ]
