# Generated by Django 6.0.2 on 2026-02-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0005_gisaquestion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaquestion',
            name='choice_1_image',
            field=models.ImageField(blank=True, upload_to='gisa/questions/', verbose_name='보기① 이미지'),
        ),
        migrations.AddField(
            model_name='gisaquestion',
            name='choice_2_image',
            field=models.ImageField(blank=True, upload_to='gisa/questions/', verbose_name='보기② 이미지'),
        ),
        migrations.AddField(
            model_name='gisaquestion',
            name='choice_3_image',
            field=models.ImageField(blank=True, upload_to='gisa/questions/', verbose_name='보기③ 이미지'),
        ),
        migrations.AddField(
            model_name='gisaquestion',
            name='choice_4_image',
            field=models.ImageField(blank=True, upload_to='gisa/questions/', verbose_name='보기④ 이미지'),
        ),
        migrations.AddField(
            model_name='gisaquestion',
            name='text_image',
            field=models.ImageField(blank=True, upload_to='gisa/questions/', verbose_name='문제 이미지'),
        ),
    ]
