# Generated by Django 6.0.2 on 2026-03-18 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0006_gisaquestion_choice_1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='용어')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.certification', verbose_name='자격증')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisasubject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '용어',
                'verbose_name_plural': '용어집',
                'ordering': ['subject__order', 'term'],
                'unique_together': {('certification', 'subject', 'term')},
            },
        ),
    ]
