# Generated by Django 6.0.2 on 2026-04-04 12:51

import gisa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0007_gisaglossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaquestion',
            name='choice_1_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._gisa_question_img_path, verbose_name='보기① 이미지'),
        ),
        migrations.AlterField(
            model_name='gisaquestion',
            name='choice_2_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._gisa_question_img_path, verbose_name='보기② 이미지'),
        ),
        migrations.AlterField(
            model_name='gisaquestion',
            name='choice_3_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._gisa_question_img_path, verbose_name='보기③ 이미지'),
        ),
        migrations.AlterField(
            model_name='gisaquestion',
            name='choice_4_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._gisa_question_img_path, verbose_name='보기④ 이미지'),
        ),
        migrations.AlterField(
            model_name='gisaquestion',
            name='text_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._gisa_question_img_path, verbose_name='문제 이미지'),
        ),
    ]
