# Generated by Django 6.0.2 on 2026-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0008_alter_gisaquestion_choice_1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaattempt',
            name='mode',
            field=models.CharField(choices=[('exam', '풀이모드'), ('mock', '모의고사'), ('wrong_retry', '오답재풀이'), ('wrong_review', '오답복습')], default='exam', max_length=20, verbose_name='풀이유형'),
        ),
    ]
