# Generated by Django 6.0.2 on 2026-05-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0009_alter_gisaattempt_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=1, verbose_name='세대')),
                ('seen_question_ids', models.JSONField(default=list, verbose_name='이번 세대에 출제된 문제 ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 갱신')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_generations', to='gisa.certification', verbose_name='자격증')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_generations', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '모의고사 세대',
                'verbose_name_plural': '모의고사 세대',
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
