# Generated by Django 6.0.2 on 2026-06-07 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0011_reset_mock_generation_to_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(blank=True, default='', max_length=20, verbose_name='탭')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='시각')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='gisa.certification', verbose_name='자격증')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_views', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '자격증 페이지 조회',
                'verbose_name_plural': '자격증 페이지 조회',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='gisa_certif_viewed__8a13ea_idx'), models.Index(fields=['user', 'viewed_at'], name='gisa_certif_user_id_80e5fa_idx'), models.Index(fields=['certification', 'tab', 'viewed_at'], name='gisa_certif_certifi_719572_idx')],
            },
        ),
    ]
