# Generated by Django 6.0.2 on 2026-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0012_certificationviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaquestion',
            name='freq_tier',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='1~5 (5가 최다 빈출). 0은 미산정 — 별표를 표시하지 않는다.', verbose_name='빈출 등급'),
        ),
    ]
