# Generated by Django 6.0.2 on 2026-08-24 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0013_gisaquestion_freq_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='학습시각')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisaquestion', verbose_name='문제')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '학습기록',
                'verbose_name_plural': '학습기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'question'], name='gisa_gisast_user_id_c90bf5_idx')],
            },
        ),
    ]
