# Generated by Django 6.0.2 on 2026-09-01 01:09

import django.db.models.deletion
import gisa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0015_backfill_studylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaEssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('예상', '예상문제'), ('기출', '기출문제')], default='기출', max_length=10, verbose_name='출처')),
                ('section', models.CharField(blank=True, help_text='예상문제의 소절명(생태학·법규 등). 기출은 "기출"', max_length=30, verbose_name='영역')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='출제연도')),
                ('round', models.IntegerField(blank=True, null=True, verbose_name='회차')),
                ('number', models.IntegerField(verbose_name='문항번호')),
                ('qtype', models.CharField(choices=[('열거', '열거형'), ('서술', '서술형'), ('단답', '단답형'), ('빈칸', '빈칸형'), ('계산', '계산형'), ('표그림', '표·그림형')], default='서술', max_length=10, verbose_name='유형')),
                ('text', models.TextField(verbose_name='문제')),
                ('text_image', models.ImageField(blank=True, upload_to=gisa.models._essay_question_img_path, verbose_name='문제 이미지')),
                ('answer_items', models.JSONField(blank=True, default=list, help_text='채점 포인트 단위 리스트', verbose_name='답 항목')),
                ('answer_text', models.TextField(blank=True, help_text='표·계산식 등 항목화하기 어려운 답', verbose_name='답 서술')),
                ('answer_image', models.ImageField(blank=True, upload_to=gisa.models._essay_question_img_path, verbose_name='답 이미지')),
                ('reference', models.TextField(blank=True, help_text='법조문·지침 등. 채점에는 쓰지 않고 학습용으로 노출', verbose_name='참고자료')),
                ('reference_image', models.ImageField(blank=True, upload_to=gisa.models._essay_question_img_path, verbose_name='참고 이미지')),
                ('points', models.PositiveSmallIntegerField(default=3, verbose_name='배점')),
                ('rubric', models.JSONField(blank=True, default=list, help_text='[{point, keywords[], score}] 형식. 비어 있으면 answer_items로 자동 생성', verbose_name='채점 기준표')),
                ('std_major', models.PositiveSmallIntegerField(default=0, help_text='1~8. 0은 미분류', verbose_name='출제기준 주요항목')),
                ('std_sub', models.PositiveSmallIntegerField(default=0, verbose_name='출제기준 세부항목')),
                ('notes', models.TextField(blank=True, help_text='원문 오식 등. 관리자만 확인', verbose_name='판독 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_questions', to='gisa.certification', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '실기 필답 문항',
                'verbose_name_plural': '실기 필답 문항',
                'ordering': ['source', 'section', '-year', '-round', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GisaEssaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='기출', max_length=10, verbose_name='출처')),
                ('section', models.CharField(blank=True, max_length=30, verbose_name='영역')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='출제연도')),
                ('round', models.IntegerField(blank=True, null=True, verbose_name='회차')),
                ('mode', models.CharField(choices=[('online', '온라인 입력'), ('paper', '시험지 사진')], default='online', max_length=10, verbose_name='입력방식')),
                ('status', models.CharField(choices=[('progress', '진행중'), ('grading', '채점중'), ('done', '채점완료')], default='progress', max_length=10, verbose_name='상태')),
                ('paper_code', models.CharField(blank=True, db_index=True, help_text='인쇄 시험지 QR에 담기는 세션 식별 코드', max_length=12, verbose_name='시험지 코드')),
                ('total_points', models.PositiveSmallIntegerField(default=45, verbose_name='총 배점')),
                ('score', models.FloatField(default=0, verbose_name='획득 점수')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.certification', verbose_name='자격증')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '필답 응시',
                'verbose_name_plural': '필답 응시',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GisaEssayAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='제출 답안')),
                ('transcribed_text', models.TextField(blank=True, help_text='손글씨 판독 결과. 사용자가 수정하면 answer_text에 확정본이 들어간다', verbose_name='사진 판독 원문')),
                ('transcribe_confirmed', models.BooleanField(default=False, verbose_name='판독 확인')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='AI 채점 점수')),
                ('final_score', models.FloatField(blank=True, help_text='사용자가 조정한 값. 없으면 ai_score를 쓴다', null=True, verbose_name='최종 점수')),
                ('feedback', models.JSONField(blank=True, default=dict, help_text='{points: [{point, matched, comment}], summary: str}', verbose_name='채점 상세')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='채점 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisa.gisaessayquestion', verbose_name='문항')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gisa.gisaessaysession', verbose_name='응시')),
            ],
            options={
                'verbose_name': '필답 답안',
                'verbose_name_plural': '필답 답안',
                'ordering': ['question__number'],
            },
        ),
        migrations.CreateModel(
            name='GisaEssayUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.PositiveSmallIntegerField(default=1, verbose_name='페이지')),
                ('image', models.ImageField(upload_to=gisa.models._essay_upload_path, verbose_name='사진')),
                ('transcribed', models.BooleanField(default=False, verbose_name='판독 완료')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='gisa.gisaessaysession', verbose_name='응시')),
            ],
            options={
                'verbose_name': '시험지 사진',
                'verbose_name_plural': '시험지 사진',
                'ordering': ['session', 'page_no'],
            },
        ),
        migrations.AddIndex(
            model_name='gisaessayquestion',
            index=models.Index(fields=['certification', 'source'], name='gisa_gisaes_certifi_80ea21_idx'),
        ),
        migrations.AddIndex(
            model_name='gisaessayquestion',
            index=models.Index(fields=['certification', 'year', 'round'], name='gisa_gisaes_certifi_8021d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gisaessayquestion',
            unique_together={('certification', 'source', 'section', 'year', 'round', 'number')},
        ),
        migrations.AddIndex(
            model_name='gisaessaysession',
            index=models.Index(fields=['user', '-started_at'], name='gisa_gisaes_user_id_3f2547_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gisaessayattempt',
            unique_together={('session', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='gisaessayupload',
            unique_together={('session', 'page_no')},
        ),
    ]
