# Generated by Django 6.0.2 on 2026-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0016_gisaessayquestion_gisaessaysession_gisaessayattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='points',
            field=models.FloatField(default=3, help_text='기출은 회차 합계가 45점이 되도록 0.5점 단위로 정규화', verbose_name='배점'),
        ),
    ]
