# Generated by Django 6.0.2 on 2026-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0017_alter_gisaessayquestion_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaessayquestion',
            name='freq_note',
            field=models.CharField(blank=True, help_text='이 주제가 나온 회차 목록', max_length=200, verbose_name='출제 이력'),
        ),
        migrations.AddField(
            model_name='gisaessayquestion',
            name='freq_rounds',
            field=models.PositiveSmallIntegerField(default=0, help_text='이 주제가 출제된 회차 수. 1이면 한 번만 나온 주제', verbose_name='출제 회차 수'),
        ),
        migrations.AddField(
            model_name='gisaessayquestion',
            name='topic_key',
            field=models.CharField(blank=True, db_index=True, help_text='같은 주제로 묶인 문항이 공유하는 식별자', max_length=64, verbose_name='주제 키'),
        ),
    ]
