# Generated by Django 6.0.2 on 2026-09-02 01:24

import gisa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0018_gisaessayquestion_freq_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='reference',
            field=models.TextField(blank=True, help_text='법조문·지침·배경 설명 등. 채점에는 쓰지 않고 학습용으로 노출', verbose_name='해설'),
        ),
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='reference_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._essay_question_img_path, verbose_name='해설 이미지'),
        ),
    ]
