# Generated by Django 6.0.2 on 2026-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0019_alter_gisaessayquestion_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaessayquestion',
            name='orig_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='원본 문항번호'),
        ),
        migrations.AddField(
            model_name='gisaessayquestion',
            name='topic_group',
            field=models.PositiveSmallIntegerField(choices=[(1, '생태학 기초'), (2, '경관생태'), (3, '생태조사·분석'), (4, '복원 계획·설계'), (5, '기반환경 복원'), (6, '생태시설물·현장관리'), (7, '환경영향평가'), (8, '법규·제도')], default=0, help_text='1~8. 0은 미분류. 회차 내 문항 순서를 이 값으로 매긴다', verbose_name='주제 분류'),
        ),
    ]
