# Generated by Django 6.0.2 on 2026-09-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0020_gisaessayquestion_orig_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaEssayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='freq58 처럼 자료를 구분하는 이름', max_length=40, verbose_name='식별자')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='한 줄 설명')),
                ('content', models.TextField(verbose_name='마크다운 내용')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='표시 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_notes', to='gisa.certification', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '실기 학습자료',
                'verbose_name_plural': '실기 학습자료',
                'ordering': ['order', 'slug'],
                'unique_together': {('certification', 'slug')},
            },
        ),
    ]
