# Generated by Django 6.0.2 on 2026-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0021_gisaessaynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaessayquestion',
            name='written_freq',
            field=models.PositiveSmallIntegerField(default=0, help_text='이 문항 주제어가 필기 기출에 등장한 횟수', verbose_name='필기 등장 횟수'),
        ),
    ]
