# Generated by Django 6.0.2 on 2026-09-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0022_gisaessayquestion_written_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaessayattempt',
            name='wrong_dismissed',
            field=models.BooleanField(default=False, verbose_name='오답노트 제외'),
        ),
    ]
