# Generated by Django 6.0.2 on 2026-09-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0023_essayattempt_wrong_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='source',
            field=models.CharField(choices=[('예상', '예상문제'), ('기출', '기출문제'), ('적산', '구유형 적산')], default='기출', max_length=10, verbose_name='출처'),
        ),
    ]
