# Generated by Django 6.0.2 on 2026-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0024_alter_gisaessayquestion_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='freq_rounds',
            field=models.PositiveSmallIntegerField(default=0, help_text='이 주제가 출제된 시험지 수. 기사·산업기사를 함께 묶는 자격증은 묶음 전체의 시험지를 센다(식물보호는 9가 아니라 18이 모수)', verbose_name='출제 회차 수'),
        ),
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='topic_group',
            field=models.PositiveSmallIntegerField(default=0, help_text='0은 미분류. 이름은 essay_topics.TOPIC_GROUPS 가 자격증별로 갖는다. 회차 내 문항 순서를 이 값으로 매긴다', verbose_name='주제 분류'),
        ),
    ]
