# Generated by Django 6.0.2 on 2026-09-13 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0025_alter_gisaessayquestion_freq_rounds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True, verbose_name='일련번호')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='농약명')),
                ('category', models.CharField(choices=[('살충제', '살충제'), ('살균제', '살균제'), ('제초제', '제초제')], max_length=10, verbose_name='구분')),
                ('hint', models.CharField(blank=True, max_length=40, verbose_name='분류 단서')),
                ('whole', models.BooleanField(default=False, help_text='어미·어두로 못 가르는 것', verbose_name='통암기')),
                ('exam_count', models.IntegerField(default=0, help_text='2018~2023 기출 빈도', verbose_name='출제수')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '농약 암기카드',
                'verbose_name_plural': '농약 암기카드',
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='PesticideQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(blank=True, max_length=10, verbose_name='고른 답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시각')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gisa.pesticidecard', verbose_name='카드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_attempts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '농약 카드 풀이',
                'verbose_name_plural': '농약 카드 풀이',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'card', '-created_at'], name='gisa_pestic_user_id_888873_idx')],
            },
        ),
    ]
