# Generated by Django 6.0.2 on 2026-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0026_pesticidecard_pesticidequizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidecard',
            name='action',
            field=models.CharField(blank=True, help_text='어떻게 듣는가 (침투이행·접촉·훈증 …)', max_length=120, verbose_name='작용'),
        ),
        migrations.AddField(
            model_name='pesticidecard',
            name='family',
            field=models.CharField(blank=True, max_length=40, verbose_name='계열'),
        ),
        migrations.AddField(
            model_name='pesticidecard',
            name='target',
            field=models.CharField(blank=True, max_length=120, verbose_name='주요 대상'),
        ),
    ]
