# Generated by Django 6.0.2 on 2026-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0027_pesticidecard_action_pesticidecard_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidecard',
            name='en_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='영문명'),
        ),
    ]
