# Generated by Django 6.0.2 on 2026-09-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0028_pesticidecard_en_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True, verbose_name='일련번호')),
                ('slide', models.IntegerField(unique=True, verbose_name='슬라이드 번호')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='해충명')),
                ('group', models.CharField(blank=True, choices=[('농작물', '농작물'), ('수목', '수목')], max_length=10, verbose_name='구분')),
                ('image', models.ImageField(upload_to='pests/', verbose_name='사진')),
                ('desc', models.TextField(blank=True, verbose_name='설명')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '해충 암기카드',
                'verbose_name_plural': '해충 암기카드',
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='PestQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(blank=True, max_length=60, verbose_name='고른 답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시각')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gisa.pestcard', verbose_name='카드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_attempts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '해충 카드 풀이',
                'verbose_name_plural': '해충 카드 풀이',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'card', '-created_at'], name='gisa_pestqu_user_id_ebb726_idx')],
            },
        ),
    ]
