# Generated by Django 6.0.2 on 2026-09-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0029_pestcard_pestquizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaessaysession',
            name='mode',
            field=models.CharField(choices=[('online', '온라인 입력'), ('paper', '시험지 사진'), ('quiz', '퀴즈')], default='online', max_length=10, verbose_name='입력방식'),
        ),
    ]
