# Generated by Django 6.0.2 on 2026-09-14 12:42

import gisa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0030_essaysession_quiz_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaessayupload',
            name='flat_image',
            field=models.ImageField(blank=True, upload_to=gisa.models._essay_flat_path, verbose_name='편 사진'),
        ),
        migrations.AddField(
            model_name='gisaessayupload',
            name='flat_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='보정 정보'),
        ),
        migrations.AddField(
            model_name='gisaessayupload',
            name='flat_method',
            field=models.CharField(blank=True, max_length=10, verbose_name='보정 방법'),
        ),
    ]
