# Generated by Django 6.0.2 on 2026-09-15 13:40

import django.db.models.deletion
import gisa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0031_essayupload_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaessayquestion',
            name='source',
            field=models.CharField(choices=[('예상', '예상문제'), ('기출', '기출문제'), ('적산', '구유형 적산'), ('학원', '학원예상시험')], default='기출', max_length=10, verbose_name='출처'),
        ),
        migrations.CreateModel(
            name='GisaDrawingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='출제연도')),
                ('round', models.IntegerField(blank=True, null=True, verbose_name='회차')),
                ('title', models.CharField(help_text='예: 근린공원, 주택정원, 옥상정원', max_length=100, verbose_name='과제(대상지)')),
                ('drawings', models.JSONField(blank=True, default=list, help_text='["설계개념도", "배식설계도", "단면도"] 처럼', verbose_name='요구 도면')),
                ('scale', models.CharField(blank=True, max_length=40, verbose_name='축척')),
                ('site_area', models.CharField(blank=True, max_length=60, verbose_name='대상지 규모')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('conditions', models.TextField(blank=True, help_text='마크다운', verbose_name='요구조건')),
                ('commentary', models.TextField(blank=True, help_text='마크다운', verbose_name='해설')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='같은 회차 안 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_tasks', to='gisa.certification', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '실기 작업형 과제',
                'verbose_name_plural': '실기 작업형 과제',
                'ordering': ['-year', '-round', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GisaDrawingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('site', '현황도'), ('answer', '모범 도면'), ('ref', '참고')], default='answer', max_length=10, verbose_name='종류')),
                ('image', models.ImageField(upload_to=gisa.models._drawing_img_path, verbose_name='그림')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='설명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gisa.gisadrawingtask', verbose_name='과제')),
            ],
            options={
                'verbose_name': '작업형 도면 그림',
                'verbose_name_plural': '작업형 도면 그림',
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
