# Generated by Django 6.0.2 on 2026-09-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0032_drawing_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisadrawingtask',
            name='code',
            field=models.CharField(blank=True, help_text='수험 자료의 도면 번호 — 예: 412', max_length=10, verbose_name='도면 번호'),
        ),
        migrations.AddField(
            model_name='gisadrawingtask',
            name='pass_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='합격률(%)'),
        ),
        migrations.AlterField(
            model_name='gisadrawingtask',
            name='title',
            field=models.CharField(help_text='예: 근린 공원, 주택 정원, 옥상', max_length=100, verbose_name='과제(대상지)'),
        ),
        migrations.AlterUniqueTogether(
            name='gisadrawingtask',
            unique_together={('certification', 'year', 'round')},
        ),
    ]
