# Generated by Django 6.0.2 on 2026-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0033_drawing_code_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisadrawingtask',
            name='forecast',
            field=models.JSONField(blank=True, default=dict, verbose_name='출제 예상 투표'),
        ),
    ]
