# Generated by Django 6.0.2 on 2026-09-15 14:35

import django.db.models.deletion
import gisa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0034_drawing_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaDrawingRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='도면 번호')),
                ('title', models.CharField(max_length=100, verbose_name='도면명')),
                ('content', models.TextField(blank=True, verbose_name='자료(마크다운)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_refs', to='gisa.certification', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '기출 도면 자료',
                'verbose_name_plural': '기출 도면 자료',
                'unique_together': {('certification', 'code', 'title')},
            },
        ),
        migrations.CreateModel(
            name='GisaDrawingRefImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gisa.models._drawing_ref_img_path, verbose_name='그림')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='설명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gisa.gisadrawingref', verbose_name='도면 자료')),
            ],
            options={
                'verbose_name': '기출 도면 그림',
                'verbose_name_plural': '기출 도면 그림',
                'ordering': ['order', 'id'],
            },
        ),
    ]
