# Generated by Django 6.0.2 on 2026-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0035_drawing_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gisadrawingref',
            options={'ordering': ['order', 'id'], 'verbose_name': '기출 도면 자료', 'verbose_name_plural': '기출 도면 자료'},
        ),
        migrations.AlterUniqueTogether(
            name='gisadrawingref',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gisadrawingref',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='탭 순서'),
        ),
        migrations.AddField(
            model_name='gisadrawingref',
            name='source',
            field=models.CharField(blank=True, help_text='한 도면에 자료가 여러 벌이면 탭 이름이 된다 (예: 사용자 A, 성운)', max_length=40, verbose_name='자료 이름'),
        ),
        migrations.AlterUniqueTogether(
            name='gisadrawingref',
            unique_together={('certification', 'code', 'title', 'source')},
        ),
    ]
