# Generated by Django 6.0.2 on 2026-09-21 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0036_alter_gisadrawingref_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('written', '필기'), ('practical', '실기'), ('both', '공통')], default='written', max_length=10, verbose_name='구분')),
                ('kind', models.CharField(choices=[('youtube', '유튜브'), ('blog', '블로그·글'), ('site', '사이트'), ('file', '내려받기')], default='youtube', max_length=10, verbose_name='유형')),
                ('url', models.URLField(max_length=500, verbose_name='주소')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('author', models.CharField(blank=True, help_text='채널명·블로그명. oEmbed 로 자동으로 채워진다', max_length=100, verbose_name='출처')),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='영상 id')),
                ('start_sec', models.PositiveIntegerField(default=0, verbose_name='시작 초')),
                ('note', models.CharField(blank=True, help_text='"배액 계산만 10분" 처럼 무엇에 쓰는 자료인지. 직접 적는다', max_length=200, verbose_name='한 줄 설명')),
                ('topic_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='주제 키')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출')),
                ('is_dead', models.BooleanField(default=False, verbose_name='끊긴 링크')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 시각')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='열람 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='gisa.certification', verbose_name='자격증')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='gisa.gisasubject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '학습 자료',
                'verbose_name_plural': '학습 자료',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['certification', 'part', 'is_active'], name='gisa_gisare_certifi_04be87_idx')],
            },
        ),
    ]
