# Generated by Django 6.0.2 on 2026-09-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0037_gisaresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisaresource',
            name='part',
            field=models.CharField(choices=[('written', '필기'), ('practical', '실기 필답형'), ('work', '실기 작업형'), ('both', '공통')], default='written', max_length=10, verbose_name='구분'),
        ),
    ]
