# Generated by Django 6.0.2 on 2026-09-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0038_alter_gisaresource_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaresource',
            name='embeddable',
            field=models.BooleanField(default=True, verbose_name='퍼가기 가능'),
        ),
    ]
