# Generated by Django 6.0.2 on 2026-09-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0039_gisaresource_embeddable'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisaVideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('written', '필기'), ('practical', '실기 필답형'), ('work', '실기 작업형'), ('both', '공통')], default='work', max_length=10, verbose_name='구분')),
                ('name', models.CharField(max_length=60, verbose_name='이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_categories', to='gisa.certification', verbose_name='자격증')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gisa.gisavideocategory', verbose_name='상위 분류')),
            ],
            options={
                'verbose_name': '동영상 분류',
                'verbose_name_plural': '동영상 분류',
                'ordering': ['order', 'id'],
                'unique_together': {('certification', 'part', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gisaresource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='gisa.gisavideocategory', verbose_name='동영상 분류'),
        ),
    ]
