# Generated by Django 6.0.2 on 2026-09-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0040_gisavideocategory_gisaresource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaresource',
            name='drawing_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='도면 번호'),
        ),
    ]
