# Generated by Django 6.0.2 on 2026-09-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0041_gisaresource_drawing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisaresource',
            name='summary',
            field=models.TextField(blank=True, verbose_name='AI 요약'),
        ),
        migrations.AddField(
            model_name='gisaresource',
            name='summary_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='요약 시각'),
        ),
    ]
