# Generated by Django 6.0.2 on 2026-09-24 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisa', '0042_gisaresource_summary_gisaresource_summary_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=30, verbose_name='모눈종이')),
                ('title', models.CharField(max_length=100, verbose_name='도면 이름')),
                ('data', models.JSONField(default=dict, verbose_name='도면 자료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든 날')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='고친 날')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_drawings', to='gisa.certification', verbose_name='자격증')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_drawings', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': 'CAD 도면',
                'verbose_name_plural': 'CAD 도면',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CadSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='이름')),
                ('data', models.JSONField(default=dict, verbose_name='기호 자료')),
                ('shared', models.BooleanField(default=False, verbose_name='모두에게 공유')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='고친 날')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_symbols', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'CAD 라이브러리 기호',
                'verbose_name_plural': 'CAD 라이브러리 기호',
                'ordering': ['name', 'id'],
            },
        ),
    ]
